/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
      "background": "#0b1323",
      "error": "#ffb4ab",
      "error-container": "#93000a",
      "inverse-on-surface": "#283041",
      "inverse-primary": "#494bd6",
      "inverse-surface": "#dbe2f8",
      "on-background": "#dbe2f8",
      "on-error": "#690005",
      "on-error-container": "#ffdad6",
      "on-primary": "#1000a9",
      "on-primary-container": "#0d0096",
      "on-primary-fixed": "#07006c",
      "on-primary-fixed-variant": "#2f2ebe",
      "on-secondary": "#003640",
      "on-secondary-container": "#00424e",
      "on-secondary-fixed": "#001f26",
      "on-secondary-fixed-variant": "#004e5c",
      "on-surface": "#dbe2f8",
      "on-surface-variant": "#c7c4d7",
      "on-tertiary": "#003824",
      "on-tertiary-container": "#000703",
      "on-tertiary-fixed": "#002113",
      "on-tertiary-fixed-variant": "#005236",
      "outline": "#908fa0",
      "outline-variant": "#464554",
      "primary": "#c0c1ff",
      "primary-container": "#8083ff",
      "primary-fixed": "#e1e0ff",
      "primary-fixed-dim": "#c0c1ff",
      "secondary": "#4cd7f6",
      "secondary-container": "#03b5d3",
      "secondary-fixed": "#acedff",
      "secondary-fixed-dim": "#4cd7f6",
      "surface": "#0b1323",
      "surface-bright": "#31394a",
      "surface-container": "#18202f",
      "surface-container-high": "#222a3a",
      "surface-container-highest": "#2d3546",
      "surface-container-low": "#131c2b",
      "surface-container-lowest": "#060e1d",
      "surface-dim": "#0b1323",
      "surface-tint": "#c0c1ff",
      "surface-variant": "#2d3546",
      "tertiary": "#4edea3",
      "tertiary-container": "#00885d",
      "tertiary-fixed": "#6ffbbe",
      "tertiary-fixed-dim": "#4edea3"
},
      spacing: {
      "gutter": "20px",
      "lg": "24px",
      "margin": "32px",
      "md": "16px",
      "sm": "8px",
      "unit": "4px",
      "xl": "48px",
      "2xl": "64px",
      "3xl": "96px",
      "xs": "4px"
},
      fontFamily: {
        'display-lg': ['Syne', 'sans-serif'],
        'headline-lg': ['Syne', 'sans-serif'],
        'headline-md': ['Syne', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'code-md': ['JetBrains Mono', 'monospace'],
        'label-caps': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', fontWeight: '800', letterSpacing: '-0.02em' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'code-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1.2', fontWeight: '600', letterSpacing: '0.1em' }],
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
